apiVersion: v1
kind: Pod
metadata:
  name: online-inference-resources
spec:
  containers:
    - name: inference
      image: ningeen/online_inference:v1
      ports:
        - name: api
          containerPort: 8000
          protocol: TCP
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "1G"
          cpu: "1"