apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-inference-deploy
  labels:
    app: online-inference
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  selector:
    matchLabels:
      app: online-inference
  template:
    metadata:
      name: online-inference
      labels:
        app: online-inference
    spec:
      containers:
        - image: ningeen/online_inference:v1
          name: online-inference-deploy
          ports:
            - containerPort: 8000