apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
spec:
  containers:
    - name: inference
      image: ningeen/online_inference:v2
      ports:
        - name: api
          containerPort: 8000
          protocol: TCP
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "1G"
          cpu: "1"
      readinessProbe:
        httpGet:
          path: /readiness
          port: 8000
        initialDelaySeconds: 30
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /liveness
          port: 8000
        initialDelaySeconds: 90
        periodSeconds: 5