version: '3.7'
# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-environment: &airflow_environment
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
  - AIRFLOW__SMTP__SMTP_STARTTLS=True
  - AIRFLOW__SMTP__SSL=False
  - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
  - AIRFLOW__SMTP__SMTP_PORT=587
  - AIRFLOW__SMTP__SMTP_USER=${GMAIL_APP_USERNAME}
  - AIRFLOW__SMTP__SMTP_MAIL_FROM=${GMAIL_APP_USERNAME}
  - AIRFLOW__SMTP__SMTP_PASSWORD=${GMAIL_APP_PASSWORD}
  - AIRFLOW_VAR_GMAIL_USER=${GMAIL_USER}
  - VOLUME_PATH=/home/ningeen/Documents/repos/ml_in_prod/airflow_ml_dags


x-airflow-image: &airflow_image apache/airflow:2.0.0-python3.6
# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================
services:
  postgres:
    build:
      context: images/airflow-postgres
    image: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_MULTIPLE_DATABASES=airflow,mlflow
    networks:
      - airflow-net
    ports:
      - "5432:5432"
  init:
    build:
      context: images/airflow-docker
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: airflow-docker
    networks:
      - airflow-net
    depends_on:
      - postgres
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: >-
      -c 'airflow db init
      && airflow users create
      --username admin --password admin
      --firstname Anonymous --lastname Admin
      --role Admin --email admin@example.org
      && airflow connections add fs_default --conn-type fs'

  webserver:
    build:
      context: images/airflow-docker
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: airflow-docker

    restart: always
    depends_on:
      - postgres
    networks:
      - airflow-net
    ports:
      - "8080:8080"
    volumes:
      - logs:/opt/airflow/logs
    environment: *airflow_environment
    command: webserver

  scheduler:
    build:
      context: images/airflow-docker
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: airflow-docker
    networks:
      - airflow-net
    restart: always
    depends_on:
      - postgres
    volumes:
      - logs:/opt/airflow/logs
      - ./dags/:/opt/airflow/dags/
      - ./data/:/opt/airflow/data/
      - ./models/:/opt/airflow/models/
      - /var/run/docker.sock:/var/run/docker.sock
    environment: *airflow_environment
    command: scheduler

  generator:
    build:
      context: images/airflow-generator
    image: airflow-generator
    restart: "no"

  predict:
    build:
      context: images/airflow-predict
    image: airflow-predict
    restart: "no"

  preprocessor:
    build:
      context: images/airflow-preprocessor
    image: airflow-preprocessor
    restart: "no"

  scorer:
    build:
      context: images/airflow-scorer
    image: airflow-scorer
    restart: "no"

  splitter:
    build:
      context: images/airflow-splitter
    image: airflow-splitter
    restart: "no"

  trainer:
    build:
      context: images/airflow-trainer
    image: airflow-trainer
    restart: "no"

  mlflow:
    build:
      context: images/airflow-mlflow
    image:
      airflow-mlflow
    networks:
      - airflow-net
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - mlrun_data:/mlruns
    command:
      - sh  # enable var  substitution
      - -c
      - mlflow server
          --host 0.0.0.0
          --port 5000
          --backend-store-uri postgresql://airflow:airflow@postgres:5432/mlflow
          --default-artifact-root /mlruns

volumes:
  logs:
  mlrun_data:
    name: mlrun_data

networks:
  airflow-net:
    name: airflow-net