column_names:
  - "age"
  - "sex"
  - "cp"
  - "trestbps"
  - "chol"
  - "fbs"
  - "restecg"
  - "thalach"
  - "exang"
  - "oldpeak"
  - "slope"
  - "ca"
  - "thal"
dataset_size: 100
probability: 0.05
target_col: "target"
target_threshold: 50
threshold_col: "age"
limits:
  "age":
    - 20
    - 80
  "sex":
    - 0
    - 1
  "cp":
    - 0
    - 3
  "trestbps":
    - 90
    - 200
  "chol":
    - 120
    - 570
  "fbs":
    - 0
    - 1
  "restecg":
    - 0
    - 2
  "thalach":
    - 70
    - 210
  "exang":
    - 0
    - 1
  "oldpeak":
    - 0
    - 7
  "slope":
    - 0
    - 2
  "ca":
    - 0
    - 4
  "thal":
    - 0
    - 3
